CREATE SCHEMA TEC_STORE;

USE TEC_STORE;

CREATE TABLE users (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
password VARCHAR (255) NOT NULL,
dni INT UNSIGNED NOT NULL,
email VARCHAR (50) UNIQUE NOT NULL,
sex VARCHAR (50),
image VARCHAR (50),
terms INT,
typeuser_id INT UNSIGNED,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE typeusers (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
coustomer INT UNSIGNED NOT NULL,
admin INT UNSIGNED NOT NULL,
superadmin INT UNSIGNED NOT NULL,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE products (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
price INT UNSIGNED NOT NULL,
discount INT UNSIGNED NOT NULL DEFAULT 0,
description VARCHAR (255) NOT NULL,
code VARCHAR (50) NOT NULL,
image VARCHAR (50),
stock INT UNSIGNED NOT NULL,
category_id INT UNSIGNED,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE categories (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
active INT UNSIGNED NOT NULL DEFAULT 1,
category_offer INT UNSIGNED NOT NULL DEFAULT 0,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE orders (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
date DATE NOT NULL,
total INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE items (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
unit_price INT UNSIGNED NOT NULL,
quantity INT UNSIGNED NOT NULL,
subtotal INT UNSIGNED NOT NULL,
image VARCHAR (50) NOT NULL,
order_id INT UNSIGNED NOT NULL,
product_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE shipments (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
date DATE NOT NULL,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

CREATE TABLE order_shipment (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
order_id INT UNSIGNED NOT NULL,
shipment_id INT UNSIGNED NOT NULL,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
deleted_at DATETIME

);

ALTER TABLE users
ADD FOREIGN KEY (typeuser_id) REFERENCES typeusers(id);

ALTER TABLE products
ADD FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE orders
ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE items
ADD FOREIGN KEY (order_id) REFERENCES orders(id),
ADD FOREIGN KEY (product_id) REFERENCES products(id),
ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE order_shipment
ADD FOREIGN KEY (order_id) REFERENCES orders(id),
ADD FOREIGN KEY (shipment_id) REFERENCES shipments(id);



